### ISSUE TITLE
Suggestion: Nested FromLuaMulti

### ISSUE THREAD

**Issue by Caellian** [kyren/piccolo#38]
Hi, I recently created a [PR](https://github.com/amethyst/rlua/pull/287) on `rlua` that adds ability to nest `MultiValue`s which makes it very convenient to allow new kinds of parameter unpacking in registered functions. It hasn't been accepted yet, but I propose this addition to piccolo as well.

The PR contains very verbose explanation of these changes as well as use case examples.

I find it weird that `from_lua_multi` can take any number of arguments without telling the caller how many were consumed (which can be ignored if not needed). I do see that it's only really intended for function arguments and `Variadic` is just a nicety that comes from it, but given that something like this greatly improved DX on my project I think it could be a useful to others as well.

**Comment by kyren** [comment]
I glanced at the PR, and I definitely get the use case of handling points (pairs of xy floats, etc) more easily when they don't come last in the argument list.

Piccolo's `IntoMultiValue` and `FromMultiValue` are pretty different from rlua / mlua though and are purposefully sort of limited. For example, in piccolo, `IntoValue` / `IntoMultiValue` are not allowed to fail, and none of the conversion traits are allowed to execute code (this is essential to the design of piccolo). This is unrelated to the suggestion, I'm just providing some context.

The reason though that piccolo can get away with a more limited conversion traits is that they're not the lowest level interface for dealing with conversion, *`Stack`* is.

`Stack` I think makes the need for such a PR (at least, as it is) vastly less here, because you never set up an argument list in callbacks at all in the first place, you get a `Stack` (which is a growable slice of the top of the internal Lua stack which is itself a Vec of values) to take arguments from and return arguments back to Lua. So, it would be pretty straightforward to add your own functions to consume a number of values off of the front of the stack and return a point, or to consume values via `FromMultiValue` as separate steps, rather than one single tuple type.

I think there are two *small* missing pieces here in piccolo right now:

1) `Stack` does not allow you to push multi-values to the beginning / end or pop multi-values from the beginning / end without consuming / replacing the entire stack. This is a simple matter of adding a few new stack methods.
2) The *top-level* where Rust calls into Lua doesn't use `Stack`, it uses `IntoMultiValue` and `FromMultiValue`, but even this is artificial because those immediately go into the Lua stack. There should be more "bottom level" functions that take argument-setup callbacks which can manipulate the stack directly, then every interaction with the lua stack from Rust can be actually directly manipulate `Stack`. In `piccolo` though this is almost *just* the top-level `Executor`, and the number of places where Rust is calling into Lua at the very top level is usually vastly dwarfed by callbacks.

But even without me doing anything, it is still pretty easy *right now* to make your own functions to pop two values off of the front of the stack and return some kind of Point (or error), or push two values to the end of the stack, this is just sort of an unexpected (to me) benefit of dealing directly with the stack rather than an argument signature and automatic conversion.

**Comment by kyren** [comment]
You know what, after I said all that, it would be *extremely* easy to change `IntoMultiValue` `FromMultiValue` impls for tuples to support multi-values on the inside, they're based on iterators not Vec so this is extremely easy. Plus, exposing everywhere from the "outside" that uses `IntoMultiValue` / `FromMultiValue` to the existence of callbacks is a headache. I'll keep it in mind as an idea!

**Comment by kyren** [comment]
Yeah, I just went ahead and did it, now that I think about it some more I don't actually think it's a very big deal: 24a2c1683c1ec879fd2e90985a6307a7aa3401e3

**Comment by Caellian** [comment]
Thanks for the in-depth explanation of differences. I love how passionate you are about this project.

When I was initially adding this to rlua I was like "uhm... wouldn't need as many copies if MultiValue was a mutable reference to an iterator". I was wrong as failing to match a `Variadic` obviously requires backtracking, but an interface where it's a _forkable_ iterator would be **much** cleaner than having a separate counter.

Anyway, glad this helped simplify piccolo implementation a little. I'll borrow how you've avoided matching empty tuple in mine, didn't think of that.

**Comment by kyren** [comment]
I don't think you'd want a forkable iterator, I think if something earlier in the list consumes all of the values they should just be consumed, and that's it. In the footgun example, the first Variadic would contain all of the values and the second would be empty.

I think that's the most sensible behavior anyway, I can't think of another that's more consistent.
