### ISSUE TITLE
question

### ISSUE THREAD

**Issue by MurdeRM3L0DY** [kyren/piccolo#39]
Hello, I would like to know what you had envisioned for the rust API <-> lua binding. What's the progress on that front and how one could contribute? Thanks.

**Comment by kyren** [comment]
Nearly all of my effort so far has been in finishing what could be considered the *bottom* layer, so the most direct, raw system for Rust <-> Lua binding by creating Rust callbacks and Rust "userdata" available to Lua. The current status of this is that it works really well, in certain cases better than the equivalent functionality in the standard "Lua C API" shared by all PUC-Rio Lua forks (luajit, luau, etc...)

It is more or less similar to the functionality in mlua / rlua for creating bindings, you can create callbacks, and sometimes userdata with metatables that make `udata:my_method()` style method calls work.

All of it is very under-documented, but it's actually pretty complete right now. One thing coming in the next release is the `piccolo-util` crate, which has some super simple, [quick "userdata with methods" functionality](https://github.com/kyren/piccolo/blob/master/util/src/user_methods.rs) in it that's easier to understand than doing the same thing manually, but you can see from the implementation that it's not doing anything you can't already do yourself.

Really, the next big task should be *documenting what's there now*, because even though I can't know for sure, chances are that whatever you're looking for right now, you can already do, even if it's more verbose currently than it could be.

What I'm describing though is all pretty low level still, nothing more than what rlua / mlua provides which is very manual (and there's also no equivalent to mlua's `chunk` macro). One thing that could be on the roadmap someday but hasn't been started (and I haven't even thought deeply) is wasm-bindgen's `#[wasm_bindgen]` proc macro imports / exports. That would be very neat to have, and once the *low level* functionality settles down it would be great to really get to work on making the most common cases as ergonomic as possible.

As far as contributing right now... honestly helping with examples and documentation would be great, even if it was to just hop on discord in the #piccolo channel and ask questions so I can get a better sense of what is currently the most confusing. Most of my effort recently has been on getting the last hard bits of low level functionality working (stack traces and fancy garbage collector things like finalizers and ephemeron tables), and part of this has been a lot of expected churn in the low-level API, and there is still probably more churn to go. It's hard for me to ask a contributor to build abstractions on top of a low-level API that I still feel has not stabilized enough yet.

Eventually I'd like a "piccolo book" style document full of examples, like the [pyo3 user guide](https://pyo3.rs/main/), but before then even, some well documented example programs (like the kind that live in the examples/ folder) that demonstrate different features of the API would be pretty great.

**Comment by MurdeRM3L0DY** [comment]
Awesome. I missed the discord link in the repo link. I'll ask for further inqueries over there :)
